version: '3.2'

services:
  postgres:
      image: postgres:10
      volumes:
        - pgdata:/var/lib/postgresql/data
      env_file: ./.env
      ports:
          - 5432:5432

  redis:
    image: redis:4
    ports:
        - 6379:6379


volumes:
  pgdata:
